### ISSUE TITLE
Cannot deploy to github or netlify

### ISSUE THREAD

**Issue by ethanstrominger** [mobtimeapp/mobtime#231]
@mrozbarry How do you you deploy mobti.me?  Ideally, I would like to deploy  a modified version of mobtime (see discussion on mobtime plus) to Netlify, github, heroku or other.  When I try  yarn deploy it fails with husky install error.

**Comment by ethanstrominger** [comment]
FYI, I am on vacation until Feb 9 so may not respond until then.

**Comment by mrozbarry** [comment]
I deploy to digital ocean over ssh. I don't think netlify or github would work, considering they don't support persistent backends (as far as I know). With heroku, I think they support some sort of docker deployment, and since we merged #221 , I think that might be viable.

One thing to keep in mind is that the `public` directory is static web content, and `src` is a backend node application. Deploying `public` is _easy_ in the sense that there is no compile steps, just load up a web server and serve that directory (which the node server does, too). The main issue is most of the free-tiered web hosting platforms won't let you run a custom nodejs server + redis or a docker image.

That said, if you want to stick to something free, heroku is likely your best bet, otherwise, get/rent a cheap ubuntu server machine.

In the future, the mobtime server might be centralized, meanwhile clients would be free to host on static sites, but I think that's a bit of a distant future.

**Comment by ethanstrominger** [comment]
Thanks, I will see how heroku works.  I was having trouble with the yarn deploy command with husky but your new fixes may address that.
